# Do not trigger Travis if commit message contains "(WIP)" or "#no_travis" (case-insensitive)
if: commit_message !~ /(\(WIP\)|#no_travis)/

os: linux

language: python # Can use any language here, but if it's not 'python'
                 # it becomes necessary to pass '--user' to pip when installing hererocks.
python: "3.6"

env:
  - LUA_VERSION=5.3 BUILD_VERSION=4.1 ENABLE_RENDER=1

cache:
  directories:
    # remember to "travis cache --delete" in travis CL each time a custom cached directory needs upgrade (unlike cached packages)
    - hererocks     # for hererocks (make a parent folder, then install lua inside, to make sure the folder will be used as cache)
                    # just a small optimization to cache the whole lua install, since the hererocks pip wheel is cached with .cache/pip anyway
    - tool          # for picotool
    - $HOME/.cache  # for .cache/luarocks and .cache/pip

before_install:
  # install hererocks if needed
  - |
    if [[ ! -d lua$LUA_VERSION || ! -x lua$LUA_VERSION/bin/activate ]]; then
      pip install hererocks
      pushd hererocks
      hererocks lua$LUA_VERSION --lua $LUA_VERSION -rlatest
      popd
    fi

  # activate Lua
  - source hererocks/lua$LUA_VERSION/bin/activate

install:
  # install lua packages for testing
  - luarocks install busted
  - luarocks install luacov

  # delegate submodule install (for luamin from npm)
  - pico-boots/setup.sh

before_script:
  # download picotool if needed
  # tool directory is automatically created when added to cache,
  # so it's important to check if the executable itself already exists
  - |
    if [[ ! -d tool || ! -x tool/picotool-master/p8tool ]]; then
      pushd tool
      wget https://github.com/dansanderson/picotool/archive/master.zip
      unzip master.zip
      popd
    fi
  # make a symlink to p8tool in the PATH
  - mkdir -p "$HOME/.local/bin"
  - ln -s "$(pwd)/tool/picotool-master/p8tool" "$HOME/.local/bin/p8tool"

script:
  # build game and itest to make sure everything works fine
  # (even if build fails, tests will be run independently thanks to busted)
  # disabled build_game.sh debug because character count may get over 65536
  # easily when working at the limit, and fail; while build release is what really counts
  # (although it's bad sign for us if we cannot debug the game)
  # - ./build_all_cartridges.sh debug
  - ./build_all_cartridges.sh release

  # disabled build_itest.sh in Travis until strings are compressed
  # because character count is over 65536 and that systematically failed the build
  # while build release works fine
  # - ./build_itest.sh
  # test: all utests
  - ITEST_CARTRIDGE_SUFFIX=ignore ./test.sh
  # test: all headless itests for titlemenu (ENABLE_RENDER set in env)
  - ITEST_CARTRIDGE_SUFFIX=titlemenu ./test.sh -f headless_itests -m all
  # test: all headless itests for stage (ENABLE_RENDER set in env)
  - ITEST_CARTRIDGE_SUFFIX=ingame ./test.sh -f headless_itests -m all
  # coverage
  - bash <(curl -s https://codecov.io/bash)

before_deploy:
  # zip multiple cartridges into one distributable archive
  - pushd build/v${BUILD_VERSION}_release
  - zip -r picosonic_v${BUILD_VERSION}_release_cartridges.zip .
  - popd

deploy:
  provider: releases
  api_key:
    secure: bfXQQ0AXGHgXiq0xOxhYQ2AXX/flQnxJh/+eA/HUGfwdoPDq0QTdqFA/3jEMWkJSsFKEBVKDjJGCt24QPxUIjTu91r1wyCNdL2KlNfnogRjWAVutRZxB/OC2HWR3kJtPjkFQBCsOXHBxGI3hMJL7LWr5WfNsSGMbcRMfvphxFT3ER8XBHAUEJY6roITm6noHroqQt8Uye+0+rkGqJ8QslKRqq8qBZMZeOiOrh6SBdlhsGw0KqNno/dMXQxx2ZCrh/VUeWjNvxzXe/mZjfBPbhvyecN7jz+FytEdAhdt1Dy37hhyOAkDfxLGGsH1YAAfinH8uFwoSRo0MH8fuhdXpT7jUXuAgP9/RS0FEiZDdX+J/FdncCbnoDfE9B4Dt3L3srISeiNwxKK5sx2kzyWvftK30pV1+zEgnbVEKGPIIeGb5wYWSCmzHf+CfLMk+bzeznTrpo/irY/vjoRBefNaVWXqLygrNWxM1uIMJae+OA3MYeUSYd1lpCyRw98i3GC7si68M9OaDeLoDjnqOLqvhurB/RmLzCU7mCYipn2kxykAOdevWN73cyx9VhdFy2GPE5VDw6EO6ZQP04KaeYxP2pgR4ts2kYWpVvf1PGg+2yN4QMkVhrWV+6dG2jtUO0BrCqt5Tpw0I3C3aFmBjjzFBBuKsZpr2yUG3roxnu1Dhww0=
  file: build/v${BUILD_VERSION}_release/picosonic_v${BUILD_VERSION}_release_cartridges.zip
  on:
    tags: 'true'
  skip_cleanup: 'true'
